// Split translation unit: see diff_src/*.c
#include "diff_src/00_prelude.c"
#include "diff_src/01_timing.c"
#include "diff_src/02_title_helpers.c"
#include "diff_src/03_xz.c"
#include "diff_src/04_db_parsing.c"
#include "diff_src/05_combined.c"
#include "diff_src/06_remap_edges.c"
#include "diff_src/07_graph_build.c"
#include "diff_src/08_topk.c"
#include "diff_src/09_added_removed.c"
#include "diff_src/10_pagerank.c"
#include "diff_src/11_diameter.c"
#include "diff_src/12_quantiles.c"
#include "diff_src/13_prsampler.c"
#include "diff_src/14_edge_diff.c"
#include "diff_src/15_main_analysis.c"
#include "diff_src/16_cli.c"
