name: Regenerate DB

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * 2' # run weekly

jobs:
  create-updated-wiki-dump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Build (part 1)
      run: go run ./db_gen/db_gen.go

    - name: Build (part 2)
      run: go run ./db_gen/redirect_cleaner.go

    - name: Compress
      run: 7z a db.7z db.sqlite

    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: db.7z
        tag_name: latest
        body: \*Last updated on ${{ steps.date.outputs.date }}*
