name: Regenerate DB

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 4,23 * *' # run on days 4/23 of each month (dumps start on days 1/20 and take a few days to complete)

jobs:
  create-updated-wiki-dump:
    strategy:
      fail-fast: false
      matrix:
        lang: [en, es, fr, de, zh, ja, ru, ar]

    name: ${{ matrix.lang }}wiki Dump Gen
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Prerequisites
      id: setup
      run: |
        sudo apt install -y jq
        echo "::set-output name=date::$(date +'%Y.%m.%d')"

    - name: Build (part 1)
      run: go run ./db_gen/db_gen.go ${{ matrix.lang }}

    - name: Build (part 2)
      run: go run ./db_gen/redirect_cleaner.go ${{ matrix.lang }}

    # - name: Build (part 3)
    #   run: |
    #     gcc -O3 -o migrate ./c_client/db_migrate.c -pthread -ldl
    #     ./migrate ${{ matrix.lang }}.db ${{ matrix.lang }}.bin

    - name: Compress
      # run: 7z a ${{ matrix.lang }}.db.7z ${{ matrix.lang }}.bin
      run: 7z a ${{ matrix.lang }}.db.7z ${{ matrix.lang }}.db

    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.lang }}.db.7z
        tag_name: ${{ steps.setup.outputs.date }}
