name: Regenerate DB

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 4,23 * *' # run on days 4/23 of each month (dumps start on days 1/20 and take a few days to complete)

jobs:
  create-updated-wiki-dump:
    strategy:
      fail-fast: false
      matrix:
        lang: [en, fr, de, ja, it, ru, es, zh, pl, nl, pt, ar]

    name: ${{ matrix.lang }}wiki Dump Gen
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Prerequisites
      id: setup
      run: |
        sudo apt install -y jq xz-utils
        echo "::set-output name=date::$(curl https://saimei.ftp.acc.umu.se/mirror/wikimedia.org/dumps/index.json | jq --raw-output '.wikis.enwiki.jobs.pagelinkstable.updated | split(" ") | .[0] ')"

    - name: Build
      run: |
        go run ./db_gen/db_gen.go  ${{ matrix.lang }} | xz -C crc32 -9 -f - > " ${{ matrix.lang }}.bin"

    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.lang }}.bin
        tag_name: ${{ steps.setup.outputs.date }}
