name: Update DB

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 1-2,4-21,23-31 * *' # run every day except 3/22 of each month (as true dumps are released those days)

jobs:
  update-wiki-dump:
    strategy:
      fail-fast: false
      matrix:
        lang: [en, es, fr, de, zh, ja, ru]

    name: ${{ matrix.lang }}wiki Dump Update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Prerequisites
      id: setup
      run: |
        sudo apt install -y jq
        echo "::set-output name=date::$(date +'%Y.%m.%d')"
        echo "::set-output name=yesterday::$(date +'%Y%m%d' -d 'yesterday')"

    - name: Download & extract old db
      run: |
        wget https://github.com/spaceface777/WikiGameSolver/releases/latest/download/${{ matrix.lang }}.db.7z
        7z x ${{ matrix.lang }}.db.7z
        rm -f ${{ matrix.lang }}.db.7z

    - name: Download & extract changes
      run: |
        wget -o diff.xml.bz2 https://dumps.wikimedia.org/other/incr/${{ matrix.lang }}wiki/${{ steps.setup.outputs.yesterday }}/${{ matrix.lang }}wiki-${{ steps.setup.outputs.yesterday }}-pages-meta-hist-incr.xml.bz2
        tar xf diff.xml.bz2
        rm -f diff.xml.bz2
        mv *.xml diff.xml

    - name: Update
      run: go run ./db_gen/db_gen.go ${{ matrix.lang }} diff.xml

    - name: Compress
      run: 7z a ${{ matrix.lang }}.db.7z ${{ matrix.lang }}.db

    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.lang }}.db.7z
        tag_name: ${{ steps.setup.outputs.date }}
        prerelease: true
        
